"""Init transaction_logs table

Revision ID: 5c09c55028d4
Revises: 
Create Date: 2026-03-27 11:02:13.916944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c09c55028d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_logs',
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('amount_kzt', sa.Float(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_logs_timestamp_utc'), 'transaction_logs', ['timestamp_utc'], unique=False)
    op.create_index(op.f('ix_transaction_logs_user_id'), 'transaction_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_user_id'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_timestamp_utc'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    # ### end Alembic commands ###
