"""Add Late Fusion fields

Revision ID: d4a57323f38d
Revises: 5c09c55028d4
Create Date: 2026-04-30 16:07:00.564585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a57323f38d'
down_revision: Union[str, Sequence[str], None] = '5c09c55028d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_logs', sa.Column('behavior_score', sa.Float(), nullable=True))
    op.add_column('transaction_logs', sa.Column('feature_impacts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_logs', 'feature_impacts')
    op.drop_column('transaction_logs', 'behavior_score')
    # ### end Alembic commands ###
